# Generated by Django 4.0.4 on 2022-06-02 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 17, 26, 52, 799675)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 17, 26, 52, 799675)),
        ),
        migrations.AddConstraint(
            model_name='userimage',
            constraint=models.UniqueConstraint(fields=('user', 'image'), name='user_image_primary_key'),
        ),
    ]
