# Generated by Django 4.0.4 on 2022-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_goal', '0002_user_presents_alter_user_double_prediction_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
