# Generated by Django 4.0.4 on 2022-05-20 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_goal', '0003_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 1, 4, 22, 563516)),
        ),
    ]
