# Generated by Django 4.0.4 on 2022-05-22 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_goal', '0004_news_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 2, 36, 8, 343768)),
        ),
    ]
