# Generated by Django 4.0.4 on 2022-05-23 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_goal', '0005_comment_dislike_counter_comment_like_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 16, 45, 22, 640953)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 16, 45, 22, 638902)),
        ),
    ]
