# Generated by Django 4.0.4 on 2022-05-29 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_goal', '0006_comment_date_time_alter_news_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike_counter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_counter',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 15, 37, 36, 879420)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 15, 37, 36, 879420)),
        ),
    ]
